CREATE CONSTRAINT user_id IF NOT EXISTS
FOR (u:User)
REQUIRE u.id IS UNIQUE;

CREATE CONSTRAINT ticket_id IF NOT EXISTS
FOR (t:Ticket)
REQUIRE t.id IS UNIQUE;

CREATE CONSTRAINT message_id IF NOT EXISTS
FOR (m:TicketMessage)
REQUIRE m.id IS UNIQUE;